### ISSUE TITLE
Question about physically-based insertion

### ISSUE THREAD

**Issue by phdymz** [Chen-Suyi/SIRA_Pytorch#1]
Dear author,
How do you implement physically-based insertion to avoid collision? And during "physically-based insertion", the inserted object is in the form of point cloud or mesh? Could you please provide me some reference papers about "point cloud collision detection"?

**Comment by Chen-Suyi** [comment]
1. To avoid the collision, we simply used [trimesh.collision.CollisionManager()](https://trimesh.org/trimesh.collision.html#module-trimesh.collision).
2. We inserted meshes instead of point clouds.

**Comment by phdymz** [comment]
thank you very much！！
