### ISSUE TITLE
About pip package noria2

### ISSUE THREAD

**Issue by zhangxy0517** [Chen-Suyi/SIRA_Pytorch#2]
An error occurred after I ran ``pip install -r requirements.txt``
![截图 2023-11-03 11-29-52](https://github.com/Chen-Suyi/SIRA_Pytorch/assets/42647472/fdd8e5a9-abbf-43e0-926a-3fe85b70eb1b)

Where can I download this package?

**Comment by Chen-Suyi** [comment]
Sorry for that mistake. This package will be removed from requirements.txt in the future.

Actually, nori2 is a private package for boosting data loading from remote servers, and it is NOT used in the published version of the codes.

I have double check the codes. It seems there is no file importing it. You can simply omit this package.

**Comment by zhangxy0517** [comment]
Thanks for your help!
