### ISSUE TITLE
Dataset Links are not working

### ISSUE THREAD

**Issue by HCL-91** [Chen-Suyi/SIRA_Pytorch#3]
Hello, I would like to download the FlyingShapes dataset.
However, the onedrive link seems to be down at the moment. 
Would you be able to have the link working anytime soon?

Thank you,

**Comment by Chen-Suyi** [comment]
I find the download link is still working.
You may need a VPN to help you access Onedrive or try other downloaders, e.g., IDM, if you are from the Chinese mainland.

Anyway, I will upload the dataset to BaiduDisk in late March (it takes quite a long time to upload).
I don't know if it can help you.

**Comment by HCL-91** [comment]
Thank you for the response,
I tried to download the data from a different location and found that it works fine.
